#!/usr/bin/env python3
"""Regenerate src/fontIds.h from lib/EpdFont/builtinFonts/*.h hashes.

Python port of lib/EpdFont/scripts/build-font-ids.sh (which requires Ruby).
Produces byte-identical output to the Ruby script.
"""

import hashlib
import os
import sys


def font_id(font_dir: str, files: list[str]) -> int:
    total = 0
    for name in files:
        path = os.path.join(font_dir, name)
        with open(path, "rb") as f:
            total += int(hashlib.sha256(f.read()).hexdigest(), 16)
    return total % (2 ** 32) - (2 ** 31)


GROUPS: list[tuple[str, list[str]]] = [
    ("BOOKERLY_12", ["bookerly_12_regular.h", "bookerly_12_bold.h", "bookerly_12_bolditalic.h", "bookerly_12_italic.h"]),
    ("BOOKERLY_14", ["bookerly_14_regular.h", "bookerly_14_bold.h", "bookerly_14_bolditalic.h", "bookerly_14_italic.h"]),
    ("BOOKERLY_16", ["bookerly_16_regular.h", "bookerly_16_bold.h", "bookerly_16_bolditalic.h", "bookerly_16_italic.h"]),
    ("BOOKERLY_18", ["bookerly_18_regular.h", "bookerly_18_bold.h", "bookerly_18_bolditalic.h", "bookerly_18_italic.h"]),
    ("NOTOSANS_12", ["notosans_12_regular.h", "notosans_12_bold.h", "notosans_12_bolditalic.h", "notosans_12_italic.h"]),
    ("NOTOSANS_14", ["notosans_14_regular.h", "notosans_14_bold.h", "notosans_14_bolditalic.h", "notosans_14_italic.h"]),
    ("NOTOSANS_16", ["notosans_16_regular.h", "notosans_16_bold.h", "notosans_16_bolditalic.h", "notosans_16_italic.h"]),
    ("NOTOSANS_18", ["notosans_18_regular.h", "notosans_18_bold.h", "notosans_18_bolditalic.h", "notosans_18_italic.h"]),
    ("OPENDYSLEXIC_8", ["opendyslexic_8_regular.h", "opendyslexic_8_bold.h", "opendyslexic_8_bolditalic.h", "opendyslexic_8_italic.h"]),
    ("OPENDYSLEXIC_10", ["opendyslexic_10_regular.h", "opendyslexic_10_bold.h", "opendyslexic_10_bolditalic.h", "opendyslexic_10_italic.h"]),
    ("OPENDYSLEXIC_12", ["opendyslexic_12_regular.h", "opendyslexic_12_bold.h", "opendyslexic_12_bolditalic.h", "opendyslexic_12_italic.h"]),
    ("OPENDYSLEXIC_14", ["opendyslexic_14_regular.h", "opendyslexic_14_bold.h", "opendyslexic_14_bolditalic.h", "opendyslexic_14_italic.h"]),
    ("UI_10", ["ubuntu_10_regular.h", "ubuntu_10_bold.h"]),
    ("UI_12", ["ubuntu_12_regular.h", "ubuntu_12_bold.h"]),
    ("SMALL", ["notosans_8_regular.h"]),
]


def main() -> int:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    font_dir = os.path.join(repo_root, "lib", "EpdFont", "builtinFonts")
    out_path = os.path.join(repo_root, "src", "fontIds.h")

    lines = [
        "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh",
        "#pragma once",
        "",
    ]
    for name, files in GROUPS:
        lines.append(f"#define {name}_FONT_ID ({font_id(font_dir, files)})")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
